### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by PoisonNinja** [liavt/Scheduler#12]
I disagree with the commit 8d7297d. I don't think that checkVersion should handle variable initialization. Several reasons:
- Calling checkVersion() every time we do something is very expensive
- It's also very redundant. How many times is checkVersion actually needed? We only need to update every few weeks.
- checkVersion is incorrectly named then

I like the idea of not creating global variables without a function, but I think it's in the wrong spot.

**Comment by liavt** [comment]
Agreed. But its the only function I could find that is called enough for it. init() isn't good, as it calls checkVersion(). We just need to migrate it to it's own function

**Comment by PoisonNinja** [comment]
Do variables get reset every time the scripts run?

**Comment by liavt** [comment]
Yes. Each time a new window opens, the variables need to be created

**Comment by PoisonNinja** [comment]
That's fine. I thought that each time the script runs, the variables get reintialized

**Comment by PoisonNinja** [comment]
I'm going to revert that commit and do a new one.

**Comment by PoisonNinja** [comment]
Look at 6a86410

**Comment by PoisonNinja** [comment]
nvm 6a86410 should be reverted. It breaks the length.

**Comment by PoisonNinja** [comment]
Why do we want to do this though?
