### ISSUE TITLE
Daylight Savings Time

### ISSUE THREAD

**Issue by PoisonNinja** [liavt/Scheduler#15]
The schedule doesn't account for DST, so everything is behind by one hour. This shouldn't be hardcoded though, so we need a solution to detect if we are observing DST.

**Comment by PoisonNinja** [comment]
Temporarily fixed by 5e45f9e

**Comment by liavt** [comment]
Fixed this. It was a problem with the time zone of the document. It was set to central time in new mexico, which doesn't account for DST. Setting it to central time in US fixed it. People have to redownload though.

**Comment by PoisonNinja** [comment]
This was fixed code side, so we can push the fix to the master spreadsheet. This means that people wouldn't have to redownload, and it'll last until the end of the school year.

**Comment by liavt** [comment]
They are already told to redownload the spreadsheet. Anyways, I want them to, because I added a field in the client called 'version.' Basically, the version is split between the client and the code, so we can make them update the spreadsheet.
