### ISSUE TITLE
Ability to not set grade level

### ISSUE THREAD

**Issue by liavt** [liavt/Scheduler#17]
The counselors want to use this. If they just want to search up a learner, they have to enter a grade, and then they can only search one grade.

**Comment by PoisonNinja** [comment]
That's going to be really hard, considering the fact that the way that the system works only allows one spreadsheet to be loaded at a time. If they don't mind having to press a button to switch grades, I could figure something out.

**Comment by liavt** [comment]
Not relevant anymore
