### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by PoisonNinja** [liavt/Scheduler#19]
Currently, the permissions that are required appear to be too "broad" according to some people, and it seems that it is causing some concern. We need to figure out a way to minimize the permissions needed.

**Comment by liavt** [comment]
Specifically it is "manage all spreadsheets in google drive"

**Comment by PoisonNinja** [comment]
I know. I think I know of a workaround.

**Comment by liavt** [comment]
I got it only to give permissions for one file, but then I can't access Bailey's spreadsheet.

**Comment by PoisonNinja** [comment]
Same. I'm guessing you used @OnlyCurrentDoc?

**Comment by liavt** [comment]
The administration gave 2 suggestions:
- Websites, but that needs a server, which we don't have. (We can request one)
- Talking with Canvas api

**Comment by liavt** [comment]
Yea I used @OnlyCurrentDoc

**Comment by PoisonNinja** [comment]
I can build a website...

**Comment by liavt** [comment]
Making a website isn't the issue. We can just port the current code there (because it's in JS and html.)
It's hosting it. How do you make it possible for everyone to connect to it

**Comment by PoisonNinja** [comment]
Google Sites

**Comment by liavt** [comment]
Still has to work with google. I suggested that, and they said they don't want it to communicate with anyone's google drive (teacher or student)

**Comment by liavt** [comment]
Because it still needs the permission for drive to see Bailey's document

**Comment by PoisonNinja** [comment]
It won't need to, because AFAIK, you can run apps scripts under the owner's account.

**Comment by liavt** [comment]
We need to look into that. AFAIK, that still gives the owner permission over drive

**Comment by PoisonNinja** [comment]
We'll see...

**Comment by NeelPi** [comment]
Just saying the security concerns are really unreasonable

**Comment by PoisonNinja** [comment]
https://sites.google.com/a/mypisd.net/ahsscheduler/

**Comment by liavt** [comment]
Can you access a spreadsheet on Bailey's drive? If so, we can start porting

**Comment by PoisonNinja** [comment]
There is a backup of the control panel in the test folder. You can point it to that copy.

**Comment by liavt** [comment]
I see that you can insert a spreadsheet, but I don't know if you can read from it. I see that you can also insert an apps script.

**Comment by liavt** [comment]
Yea we can point to that, but how will the JS read from it

**Comment by liavt** [comment]
Can we make some sort of database? So we have one script that reads from the control panel, and puts it into the site database. Then, it reads from that to get a student's schedule.

**Comment by PoisonNinja** [comment]
The data we have is not easily represented in a database table.

**Comment by liavt** [comment]
We can use JSON, xml, or sql

**Comment by liavt** [comment]
```
<schedule>

<price>

<mod a>

<mod b>

<mod c>

</price>

</schedule
```

**Comment by liavt** [comment]
A bit messy, but may be required

**Comment by liavt** [comment]
SpreadsheetApp is allowed in webapps. We just need to use doGet(), which is called on startup

**Comment by liavt** [comment]
Ill reshare the code with you, so you can write the website from the original code

**Comment by PoisonNinja** [comment]
I have the test code, and I deployed it as a web app. There appear to be several issues so far.

**Comment by liavt** [comment]
Its the getUi()

**Comment by liavt** [comment]
Ui isn't used in web apps

**Comment by PoisonNinja** [comment]
I know. It seems that the spreadsheet stuff itself still works. We should have separated the UI from the logic.

**Comment by PoisonNinja** [comment]
https://script.google.com/a/macros/mypisd.net/s/AKfycbzs67bqhCl7Ym3v6FdCgVZOfUQfH7WkxVXBuAE6bys2/dev for the web app and https://script.google.com/a/mypisd.net/d/15DLbqGv2FZ9W0TW0LVVNGUbEa7UjHSswHtQ-tZlUTUM3HdrAvNFku64K/edit?usp=drive_web for the code.

**Comment by liavt** [comment]
In the doGet() function, you need to return the html, which means you can't just open a bunch of new windows. We need to use html hyperlinks (<a>href="link to page"</a>)

**Comment by PoisonNinja** [comment]
I did.

**Comment by liavt** [comment]
We also need to use cookies to store the user's name and grade

**Comment by PoisonNinja** [comment]
Got it. Can you look at the web app link?

**Comment by liavt** [comment]
Going

**Comment by liavt** [comment]
Perfect, so it does work. All we need to do now is to remake all the prompts and buttons and stuff

**Comment by liavt** [comment]
WE have to use embedded JS in order to change the HTML

**Comment by PoisonNinja** [comment]
We also need to figure out how to prompt the user for who they are.

**Comment by liavt** [comment]
Input box. HTML can do literally everything

**Comment by liavt** [comment]
Also now we can make stylesheets as well

**Comment by liavt** [comment]
Each time we want to make a new html, you have to make a new page on the website. Otherwise, you have to use document in embedded JS to change the html

**Comment by liavt** [comment]
Or we can assign CSS classes to stuff and in JS use document.getElementByName(name of class)

**Comment by PoisonNinja** [comment]
I just realized we can do query strings, which offers immense functionality.

**Comment by liavt** [comment]
We can also do http requests as well

**Comment by PoisonNinja** [comment]
So, for now, we can create a web page that asks them to enter their name, which we can then pass in. Based on that, it looks it up using the existing code, and the page updates based on that. The best thing is that reloading the page preserves the query string.

**Comment by liavt** [comment]
https://canvas.instructure.com/doc/api/calendar_events.html

**Comment by liavt** [comment]
Canvas has an API

**Comment by liavt** [comment]
We just have to send HTTPS requests and get an OAuth token

**Comment by PoisonNinja** [comment]
But then the facilitators will need to create an event for each class.

**Comment by liavt** [comment]
True. Yea, lets stick to spreadsheets

**Comment by liavt** [comment]
All I see is null running it.

**Comment by PoisonNinja** [comment]
You have to pass in a string. After dev, paste this: ?first=jason&last=lu. Replace it with your name

**Comment by liavt** [comment]
ah got it

**Comment by liavt** [comment]
TypeError: Cannot read property "4" from undefined. (line 72, file "Code")

Looking into that error

**Comment by PoisonNinja** [comment]
It can't access the spreadsheet.

**Comment by liavt** [comment]
Which one?

**Comment by liavt** [comment]
Line 72 is a comment for me

**Comment by PoisonNinja** [comment]
That's strange. Wait a couple minutes...

**Comment by liavt** [comment]
Oh now it wokrs

**Comment by PoisonNinja** [comment]
Try it now. I messed up. It was saying my first name was null. Try it again.

**Comment by PoisonNinja** [comment]
So, now we have a working interface.

**Comment by liavt** [comment]
Now we just need a homepage for you to insert your name and make it look nice

**Comment by PoisonNinja** [comment]
Google Sites

**Comment by liavt** [comment]
Yep

**Comment by PoisonNinja** [comment]
I'm a little concerned that it's running my account, but you shouldn't be able to do anything malicious.

**Comment by liavt** [comment]
But how are you getting the name from the url? It looks like you are just doing getSchedule(59)

**Comment by PoisonNinja** [comment]
Refresh your page.

**Comment by PoisonNinja** [comment]
Initial webpage up! https://sites.google.com/a/mypisd.net/ahsscheduler/.

**Comment by liavt** [comment]
Great! You can take a break for now, I can do the rest. I feel like I haven't helped enough here, so I will work on porting the lookup and make it look nice.

**Comment by PoisonNinja** [comment]
Do you have edit permissions?

**Comment by liavt** [comment]
Yes

**Comment by PoisonNinja** [comment]
nvm yes you do.

**Comment by liavt** [comment]
First I need to check if this method is okay before moving on

**Comment by liavt** [comment]
Because it still accesses Bailey's drive

**Comment by PoisonNinja** [comment]
I'll clean up the javascript code and remove all the useless functions.

**Comment by NeelPi** [comment]
Webpage works on mobile

**Comment by PoisonNinja** [comment]
You could actually embed the web page inside as an iframe.

**Comment by PoisonNinja** [comment]
From around 900 lines of code to about 300.

**Comment by liavt** [comment]
I saw that, and I have a lot of ideas. I want to go to Ojeda first though to see what she thinks

**Comment by liavt** [comment]
Mrs Ojeda and Bailey are both fine with it, just waiting approval from Gaschen

**Comment by PoisonNinja** [comment]
I just realized that it's using the test library. We should switch it over to the actual library.

**Comment by liavt** [comment]
This will become the actual library eventually

**Comment by PoisonNinja** [comment]
I resized the iframe. How will the spreadsheet itself update?

**Comment by liavt** [comment]
Same code we had before

**Comment by PoisonNinja** [comment]
Someone has to run the update spreadsheet functions, and the code responsible for that was removed.

**Comment by PoisonNinja** [comment]
If you're going to add it back, only add in the code that is necessary, and strip out the UI code.

**Comment by PoisonNinja** [comment]
tinyurl.com/ahsscheduler for the start page.

**Comment by liavt** [comment]
Permissions aren't working. People that aren't us can't run the script, even though its shared by link.

**Comment by PoisonNinja** [comment]
Well, grades are now working. I need to check.

**Comment by PoisonNinja** [comment]
Wait @liavt what do you mean? My personal email can run it too...

**Comment by liavt** [comment]
Ill try again. A group member tried running it and said he needs to request access

**Comment by liavt** [comment]
That was 2 hours ago, BTW. It may have changed

**Comment by PoisonNinja** [comment]
Maybe.

EDIT: I just tried in an incognito window. It worked.

**Comment by liavt** [comment]
If we need to change the schedule to a database, we have this:

https://developers.google.com/apps-script/reference/jdbc/jdbc#methods

**Comment by PoisonNinja** [comment]
nvm I just realized that I needed to sign in. Make sure that they aren't using a personal account.

**Comment by PoisonNinja** [comment]
Yeah but Google Cloud SQL costs $. The only free alternative is to self host it, but that's a hassle.

**Comment by liavt** [comment]
ah ok

**Comment by PoisonNinja** [comment]
Also, the facilitators need to be able to easily update the schedule, and maybe a database might be too much work.

**Comment by liavt** [comment]
We can petition for a server

**Comment by PoisonNinja** [comment]
We could. Did you try out the grade thing yet?

**Comment by liavt** [comment]
Yes, it works.

**Comment by PoisonNinja** [comment]
Great. I think we can close this issue then, cause it's really long

**Comment by liavt** [comment]
If we don't get approval I will reopen it

**Comment by liavt** [comment]
Nope they don't have permission. I don't know if it can't access the script or it can't access Bailey's spreadsheet

**Comment by PoisonNinja** [comment]
Sorry. Try it now. What happened was the web page was using the dev version, which requires you to sign in. I updated the link to the library based one (https://script.google.com/macros/s/AKfycbzSQO-COj7Xa8ZECVrJiFDUdOsW29K7Qh8m1GHgaaBZ_pt-gzt7/exec), so now it should work.

**Comment by PoisonNinja** [comment]
@liavt does it work now?

**Comment by liavt** [comment]
Yes

**Comment by NeelPi** [comment]
It is now broken if you guys are working on it that's fine, but if it isn't something you did then the script wont run and all it says is this
![screenshot 2016-03-16 at 4 19 56 pm](https://cloud.githubusercontent.com/assets/8358619/13829083/063793be-eb93-11e5-9388-5d0875a6cb49.png)

**Comment by PoisonNinja** [comment]
You will need to go through tinyurl.com/ahsscheduler again. The link was updated.
