### ISSUE TITLE
Stylesheet

### ISSUE THREAD

**Issue by liavt** [liavt/Scheduler#20]
I got a way to include a css stylesheet (under Stylesheet.gs)

Only problem is that I am terrible at UI design.

If you can think of a website theme and design, then I can make it in CSS

**Comment by PoisonNinja** [comment]
Material Design. http://materializecss.com/

**Comment by liavt** [comment]
Nah I think we should do our own style

**Comment by liavt** [comment]
Finished. Check out the new website. Finished re implementing all previous features, added a professional looking css (which I did myself,) and got it completely functional

**Comment by PoisonNinja** [comment]
Wow looks very nice. Good work!
