### ISSUE TITLE
Staging website?

### ISSUE THREAD

**Issue by PoisonNinja** [liavt/Scheduler#24]
Is there a website where I can test the changes? The nightly link is broken.

**Comment by liavt** [comment]
https://script.google.com/a/macros/mypisd.net/s/AKfycbxu3RD39BI1mpo6iIW2JKsFoVUM47ZhSXMrIcEk55Z5/dev?view=8&grade=8

https://docs.google.com/spreadsheets/d/1I1tOOUHjoeqWRTUcbDeO5WXNDBERg9mH3EWMa1X9cNg/edit#gid=1402272396

The second one is a special control panel for a so called 8th grade, where you can test stuff

**Comment by liavt** [comment]
https://script.google.com/a/mypisd.net/d/1YVlyjLIqFYr9oupTcEz5IUHTzLbQZq1wlb7K0mBpYpfw3Rl-DZ9yZqGh/edit?usp=drive_web

Thats the code for the unstable one

**Comment by PoisonNinja** [comment]
I don't have permission

**Comment by liavt** [comment]
Fixed

**Comment by PoisonNinja** [comment]
The control panel is still unavailable for me

**Comment by liavt** [comment]
Fixed

The roster is the old LCA roster

**Comment by PoisonNinja** [comment]
Thanks
