### ISSUE TITLE
API

### ISSUE THREAD

**Issue by PoisonNinja** [liavt/Scheduler#27]
Not really an issue, but just to track progress on implementing an API. Check off as completed
- [x] API view
- [x] API request type parsing
- [x] Forming JSON response
- [ ] Returning requested data
- [ ] Parsing returned data

Current Progress:
- API view: View 12 is the API view
- Added a new parameter: request. request=0 is for MOTD, and request=1 is for general mod schedule
- Able to create JSON response

Live at https://script.google.com/macros/s/AKfycbwblS8-vAPk5NniXH1ef8BRolyuaW62ANoGWIII0y5Ijnx2k9Ip/exec?view=12&request=1&grade=10. That is a copy of the Schedule App Unstable, and uses a personal copy of the roster that I somewhat reverse engineered.

**Comment by PoisonNinja** [comment]
Sample output:

``` JSON
{"requestType":"1","mods":[["","cohort:Aconcogua","MOD A","PM","PT","MOD B","LUNCH","LOTE","MOD C","MOD D","CLUB","","","","",""],["","cohort:Elbrus","MOD D","PM","PT","MOD A","LUNCH","MOD B","LOTE","MOD C","CLUB","","","","",""],["","cohort:Kilimanjaro","MOD C","PM","PT","MOD D","LUNCH","MOD A","MOD B","LOTE","CLUB","","","","",""],["","cohort:Denali","LOTE","PM","PT","MOD C","LUNCH","MOD D","MOD A","MOD B","CLUB","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","",""]],"times":[["","KEY","1899-12-30T15:30:00.000Z","1899-12-30T16:20:00.000Z","1899-12-30T16:40:00.000Z","1899-12-30T17:45:00.000Z","1899-12-30T18:30:00.000Z","1899-12-30T19:30:00.000Z","1899-12-30T20:20:00.000Z","1899-12-30T21:10:00.000Z","1899-12-30T22:00:00.000Z","","","","",""]]}
```

General format is:
{"requestType":"request ID", response}

**Comment by liavt** [comment]
Do you know if it will be better being a POST http request or a GET http request?

**Comment by PoisonNinja** [comment]
I would use a GET http request.

**Comment by liavt** [comment]
I think that POST would be a better option honestly, it's meant for things like this. We would also not need to use a new view and that crazy if statement in doGet

**Comment by liavt** [comment]
The new version of Scheduler has an API now.
