### ISSUE TITLE
Notifications for lunch say 12:30 AM instead of 12:30 PM 

### ISSUE THREAD

**Issue by NeelPi** [liavt/Scheduler#33]
![screenshot 2017-01-09 at 12 32 12 pm](https://cloud.githubusercontent.com/assets/8358619/21778120/b21f1b6a-d667-11e6-869a-6c7ab14dd1bb.png)

**Comment by liavt** [comment]
I did > 12 not >= 12 I am fixing it now

**Comment by liavt** [comment]
Fixed
