### ISSUE TITLE
website is only accessible from the offical domain

### ISSUE THREAD

**Issue by RyanHir** [liavt/Scheduler#35]
When I run the website within an Apache 2 server I get the grade selection page but it does not move from there. The developer console outputs `uncaught exception: [object Object]` and stays on the current page. While there is issues with HTTPS on a local machine, this is repeatable on [https://liavt.github.io/Scheduler/](https://liavt.github.io/Scheduler/) which the read-me says should always be usable code.

**Comment by RyanHir** [comment]
this may be caused by the dependency of google accounts

**Comment by liavt** [comment]
Yes, it is caused by Google. This is intentional and is for security purposes. If you want to develop locally with it, PM me your domain and I'll white list it.
