### ISSUE TITLE
Zoom present on Firefox & Chrome on Android

### ISSUE THREAD

**Issue by RyanHir** [liavt/Scheduler#36]
When using Firefox 62 on android 9.0, you can zoom into the scheduler, this is present on loading the page manually and on the home screen (even though this should not affect it). This is also present on Chrome 68 for android.

Reasons to disable zoom includes, webpage easily viewable without zoom and zooming skews the page.

A possible solution could to either completely disable zoom, or have a option in the settings. This is just an enhancement.

**Comment by liavt** [comment]
I don't think it's possible to disable that zoom, it's browser level... Plus, it doesn't hurt anybody, it only helps, so it should be keptOn Sep 10, 2018 9:30 PM, RyanH <notifications@github.com> wrote:When using Firefox 62 on android 9.0, you can zoom into the scheduler, this is present on loading the page manually and on the home screen (even though this should not affect it). This is also present on Chrome 68 for android.
Reasons to disable zoom includes, webpage easily viewable without zoom and zooming skews the page.
A possible solution could to either completely disable zoom, or have a option in the settings. This is just an enhancement.
