### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by liavt** [liavt/Scheduler#8]

**Comment by PoisonNinja** [comment]
I think we can merge firstRun with init. In init, we can do a simple check for whether a trigger exists. This also means that we only need one button. I think the update was pushed too early.

**Comment by liavt** [comment]
The trigger is for firstRun now. So when you open the document,  it will do firstRun. However, I don't like making everyone redownload now. But the live update thing works.

**Comment by liavt** [comment]
SO what we can do is pretty simple:

**Comment by liavt** [comment]
along with being able to edit colors and values of cells, I think you can also create images and assign scripts to it in code. We can update the code to do that once for everyone.

**Comment by liavt** [comment]
NVM we can't assign scripts to the image after it's made.

**Comment by liavt** [comment]
Just leave it. It works fine. It may be a bit redundant, but it's useless to make everyone update an hour after its made. I don't want to make everyone redownload anymore at all

**Comment by liavt** [comment]
I will move the triggers in firstRun() to init(). Then when firstRun() is called, a prompt will appear telling the user that the button is outdated.

**Comment by PoisonNinja** [comment]
No need. Leave firstRun as a wrapper for init. In the next update (a month away, perhaps?), we can remove the first run button.

**Comment by liavt** [comment]
Nope. Try clicking the first launch button. I already moved firstRun() to init().

**Comment by PoisonNinja** [comment]
Commit it to Github
